services:
  web:
    build: .
    command: >
      sh -c "python src/manage.py migrate &&
             python src/manage.py collectstatic --noinput &&
             gunicorn --chdir src url_shortener.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db: 
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume: