# Generated by Django 4.1.7 on 2023-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.URLField()),
                ("alias", models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
